module.exports=[ 
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts' ,
        dcs_name:"SetAlertSucceeded",
        avs_name:"SetAlertSucceeded",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts' ,
        dcs_name:"SetAlertFailed",
        avs_name:"SetAlertFailed",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts' ,
        dcs_name:"DeleteAlertSucceeded",
        avs_name:"DeleteAlertSucceeded",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts' ,
        dcs_name:"DeleteAlertFailed",
        avs_name:"DeleteAlertFailed",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts',
        dcs_name:"AlertStarted",
        avs_name:"AlertStarted",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts',
        dcs_name:"AlertStopped",
        avs_name:"AlertStopped",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts',
        dcs_name:"AlertEnteredForeground",
        avs_name:"AlertEnteredForeground",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.alerts' ,
        dcs_name:"AlertEnteredBackground",
        avs_name:"AlertEnteredBackground",
        avs_namespace:"Alerts",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackStarted",
        dcs_name:"PlaybackStarted",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackNearlyFinished",
        dcs_name:"PlaybackNearlyFinished",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackFinished",
        dcs_name:"PlaybackFinished",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"ProgressReportDelayElapsed",
        dcs_name:"ProgressReportDelayElapsed",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"ProgressReportIntervalElapsed",
        dcs_name:"ProgressReportIntervalElapsed",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackFailed",
        dcs_name:"PlaybackFailed",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackStutterStarted",
        dcs_name:"PlaybackStutterStarted",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackStutterFinished",
        dcs_name:"PlaybackStutterFinished",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackStopped",
        dcs_name:"PlaybackStopped",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackPaused",
        dcs_name:"PlaybackPaused",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackResumed",
        dcs_name:"PlaybackResumed",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"PlaybackQueueCleared",
        dcs_name:"PlaybackQueueCleared",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.audio_player',
        avs_namespace:"AudioPlayer",
        avs_name:"StreamMetadataExtracted",
        dcs_name:"StreamMetadataExtracted",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.speaker_controller',
        avs_namespace:"Speaker",
        dcs_name:"VolumeChanged",
        avs_name:"VolumeChanged",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.speaker_controller',
        avs_namespace:"Speaker",
        dcs_name:"MuteChanged",
        avs_name:"MuteChanged",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.voice_output',
        avs_namespace:"SpeechSynthesizer",
        dcs_name:"SpeechStarted",
        avs_name:"SpeechStarted",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.voice_output',
        avs_namespace:"SpeechSynthesizer",
        dcs_name:"SpeechFinished",
        avs_name:"SpeechFinished",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.voice_input',
        avs_namespace:"SpeechRecognizer",
        dcs_name:"ListenStarted",
        avs_name:"ListenStarted",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.voice_input',
        avs_namespace:"SpeechRecognizer",
        dcs_name:"ListenTimedOut",
        avs_name:"ListenTimedOut",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.playback_controller',
        avs_namespace:"PlaybackController",
        dcs_name:"PlayCommandIssued",
        avs_name:"PlayCommandIssued",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.playback_controller',
        avs_namespace:"PlaybackController",
        dcs_name:"PauseCommandIssued",
        avs_name:"PauseCommandIssued",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.playback_controller',
        avs_namespace:"PlaybackController",
        dcs_name:"NextCommandIssued",
        avs_name:"NextCommandIssued",
    },
    { 
        dcs_namespace: 'ai.dueros.device_interface.playback_controller',
        avs_namespace:"PlaybackController",
        dcs_name:"PreviousCommandIssued",
        avs_name:"PreviousCommandIssued",
    },
];
